### ISSUE TITLE
Empty search never finishes

### ISSUE THREAD

**Issue by DavidRico** [Alquimiaware/Nuget-Unity#1]
I opened nuget window, didn't write anything in the search field and clicked on search. The search progress window pops up, and never disappears, returning no result.

My guess: it might be trying to list all the packets, or it might have encountered an error and hangs there.

**Comment by Cookingsource** [comment]
Yes, it seems its trying to list all the possible nuget packages. I'll just prevent it from running when the field is empty. Thanks!
